resources:
  repositories:
    - repository: templates
      type: git
      name: ccdc-3rd-party/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: b2
    package_version: 4.2.0
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
    # We use this for building boost, so only bring it in on ubuntu where we 'build' boost headers
    build_types:
      - Release
    platforms:
      - ubuntu2004_gcc10
